<?php

/**
 * @file
 * Contains sloth.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
//use Drupal\Core\Entity\EntityInterface;
//use Drupal\Component\Utility\Html;
use Drupal\shard\ShardTagHandler;

//use Drupal\views\ViewExecutable;
use Drupal\sloth\Services\EligibleFields;
use Drupal\editor\Entity\Editor;

/**
 * Implements hook_help().
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 * @return string
 */
function sloth_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sloth module.
    case 'help.page.sloth':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Testing the shard idea with sloths.') . '</p>';
      return $output;

    default:
  }
}

//function sloth_theme($existing, $type, $theme, $path) {
//  return array(
//    'node__sloth__full' => array(
//      'template' => 'node--sloth--full'
//    ),
//  );
//}

//function sloth_theme_registry_alter(&$theme_registry) {
//  $theme_registry['node__sloth__full']['path']
//    = drupal_get_path('module', 'sloth') . '/templates/node--sloth--full';
//}

/**
 * Implements hook_preprocess().
 *
 * See https://www.drupal.org/node/2499827
 */
function sloth_preprocess(&$variables, $hook, &$info) {
  if ( $hook == 'node' ) {
    $contentTypeToShow = $variables['node']->bundle();
    if ($contentTypeToShow == 'sloth') {
      //Load the view mode names.
      $allViewModes = \Drupal::service('entity_display.repository')
        ->getViewModes('node');
      //View mode for this request.
      $viewModeToUse = $variables['view_mode'];
      //Is the view mode defined for nodes?
      if (key_exists($viewModeToUse, $allViewModes)) {
        //Is there a template file for the view modes in the module?
        $templateFileName = 'node-' . $contentTypeToShow . '-' . $viewModeToUse;
        $templateFilePath = drupal_get_path('module', 'sloth') . '/templates/'
          . $templateFileName . '.html.twig';
        if (file_exists($templateFilePath)) {
          $info['theme path'] = drupal_get_path('module', 'sloth');
          $info['path'] = drupal_get_path('module', 'sloth') . '/templates';
          $info['template'] = $templateFileName;
          $node = $variables['node'];
          $variables['sloth_name'] = $node->get('title')->value;
          $variables['sloth_id'] = $node->id();
          $variables['sloth_cuteness'] = $node->get('field_cuteness')->value;
          $variables['sloth_notes'] = $node->get('field_sloth_notes')->value;
          $variables['sloth_photo_url']
            = file_create_url($node->get('field_photo')->entity->uri->value);
          $variables['sloth_photo_alt']
            = $node->get('field_photo')->getValue()[0]['alt'];

        } //End template file exists.
      } //End view mode exists.
    } //End this is a sloth.
  } //End this is a node.
}

function sloth_node_view_alter(array &$build,
      Drupal\Core\Entity\EntityInterface $entity,
     \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display){
  if ( isset($build['#attached']) ) {
    $build['#attached']['library'][] = 'sloth/sloth.view';
  }
}

/**
 * Implements hook_ckeditor_css_alter().
 *
 * Injects our selected CSS sheet anytime CKEditor has loaded.
 *
 * @param array $css
 * @param Drupal\editor\Entity\Editor $editor
 */
function sloth_ckeditor_css_alter(array &$css, Editor $editor) {
  $css[] = base_path() . drupal_get_path('module', 'sloth') . '/css/sloth.css';
}

function sloth_form_filter_format_edit_form_alter(&$form, $formState) {
  $form['#attached']['library'][] = 'sloth/sloth.edit';
}